Event Sourcing docs
dolittle/Runtime pull request #450
Opened 2021-01-04 11:36 UTC by joelhoisko

- Added a simple diagram for event sourcing
- Added CRUD bad, event sroucing good and bad sections.
- Wrote about some of the main deals with event sourcing
- Deleted old stuff regarding aggregate specific stuff
- External links

I'm not quite sure how deep we wanna go into the whole event sourcing stuff as there is plenty of good stuff of it online so I think this is an adequate explanation for our scope for now.

2021-01-05 13:33 UTC, woksin requested changes
Overall good stuff. I do have some comments though.

I do get the feel that we probably want to revisit much of what is written in the future, but now I think that it's important to get something out there and then we can see if we can improve more later on.

2021-01-05 13:33 UTC, woksin commented on Documentation/Concepts/event_sourcing.md
> +    - The state of the application can be recreated by just applying the events. This enables rollbacks to any previous point in time.
Maybe add 're'?
```suggestion
    - The state of the application can be recreated by just re-applying the events. This enables rollbacks to any previous point in time.
```

2021-01-05 14:15 UTC, joelhoisko commented on Documentation/Concepts/event_sourcing.md
> +- Without additional auditing logs, the history of operations is lost. More importantly, the [_reason_]({{< ref "#reason-for-change" >}}) for changes is lost.
I basically took most of it from the [Microsoft Event Sourcing docs](https://docs.microsoft.com/en-us/azure/architecture/patterns/event-sourcing#context-and-problem).

2021-01-05 14:34 UTC, joelhoisko commented on Documentation/Concepts/event_sourcing.md
> +    - The event store raises events and any number of [Event Handlers]({{< ref "event_handlers_and_filters" >}}) can process the events. This separation of concerns provides great flexibility and can
Yeah, it's so easy to use the word "publish" here. How about:
```suggestion
   - The [Event Handlers]({{< ref "event_handlers_and_filters" >}}) react to events committed to the event store independently. This allows the handlers to be decoupled from the events.
```

2021-01-05 14:55 UTC, joelhoisko commented on Documentation/Concepts/event_sourcing.md
> +    - With an event store, it's easy to separate read and write operations to different databases.
How about:
```suggestion
    - With an event store, it's easy to separate change handling and state querying, allowing for easier horizontal scaling. The events and their projections can be scaled independently of each other.
```
One of the cool things about event sourcing is it's scalability so I wanna get that out there somehow.

2021-01-05 14:56 UTC, joelhoisko commented on Documentation/Concepts/event_sourcing.md
> +- Without additional auditing logs, the history of operations is lost. More importantly, the [_reason_]({{< ref "#reason-for-change" >}}) for changes is lost.
Also "why not CRUD" is there to set the stage for the real deal, "why event sourcing" that I try to answer with the advantages part.

2021-01-06 08:53 UTC, woksin commented on Documentation/Concepts/event_sourcing.md
> +- Without additional auditing logs, the history of operations is lost. More importantly, the [_reason_]({{< ref "#reason-for-change" >}}) for changes is lost.
The content is fine, I just have a problem with the header. I like the Microsoft writeup.

2021-01-06 08:57 UTC, woksin commented on Documentation/Concepts/event_sourcing.md
> +- Without additional auditing logs, the history of operations is lost. More importantly, the [_reason_]({{< ref "#reason-for-change" >}}) for changes is lost.
Since the content there in my opinion kinda describes some of the problems with a traditional approach.

2021-01-06 08:59 UTC, woksin commented on Documentation/Concepts/event_sourcing.md
> +    - The event store raises events and any number of [Event Handlers]({{< ref "event_handlers_and_filters" >}}) can process the events. This separation of concerns provides great flexibility and can
What do you mean with "...decoupled from the events"?

2021-01-06 09:26 UTC, joelhoisko commented on Documentation/Concepts/event_sourcing.md
> +    - The event store raises events and any number of [Event Handlers]({{< ref "event_handlers_and_filters" >}}) can process the events. This separation of concerns provides great flexibility and can
```suggestion
   - The [Event Handlers]({{< ref "event_handlers_and_filters" >}}) react to events committed to the event store. The handlers know about the event and its data, but they don't know or care what caused the event. This provides great flexibility and can be easily extended/integrated with other systems.
```

2021-01-06 09:27 UTC, woksin approved these changes

2021-01-06 09:32 UTC, merged