Possible fix for deadlock issue when notifying and waiting for events
dolittle/Runtime pull request #500
Opened 2021-03-11 13:57 UTC by woksin

## Summary

We saw inconsistent issues while committing events in applications with event handlers that caused the runtime to deadlock when committing an event, never returning.

Inspired by this blog post https://devblogs.microsoft.com/premier-developer/the-danger-of-taskcompletionsourcet-class/ we have a theory that it might be because when a TaskCompletionSource is being waited for and SetResult is called on it then all the task's async continuations will be invoked synchronously which could lead to a deadlock scenario. If that's the case then this issue can be resolved by giving the TaskCompletionSource the TaskCreationOptions.RunContinuationsAsynchronously flag when created to force the continuations to be run asynchronously. 

We have yet to be able to write tests that provoke this scenario. Until then we can never know whether the issue has been resolved or not, or that that was the problem to begin with.

### Changed

- Made EventWaiter more robust
- Added TaskCreationOptions.RunContinuationsAsynchronously to all manually created TaskCompletionSources

2021-03-16 14:18 UTC, woksin commented
Should we mark this as a minor? To signify that this is a "bigger" thing? We could also deprecate and remove all versions all >= 5.3.0 and <= 5.4.1

2021-03-18 08:26 UTC, jakhog requested changes
```csharp
    public class EventWaiter
    {
        readonly object _notifiedLock = new();
        readonly object _readWriteLock = new();
```

The cause of the deadlock was that there are two execution paths that captures these locks, in the opposite order. So one path would acquire `_notifiedLock` then `_readWriteLock`, while another would acquire `_readWriteLock` then `_notifiedLock`. So if one of the threads was interrupted in the middle, it would freeze the code.

The problem is alleviated with the `RunContinuationsAsynchronously`, but I think it would be nice if we weren't reliant on the scheduling to solve the deadlock issue. So my suggestion is to remove one of the locks - and just use the one.

2021-03-21 11:39 UTC, jakhog approved these changes

2021-03-21 11:41 UTC, jakhog commented
Nice! I'll pull this in as a patch trying to stay true to the SemVer scheme. And yes - we should deprecate the versions we know don't work. I'll go do it on Docker Hub - and see what we can do on the releases here.

2021-03-21 11:41 UTC, merged