Get projections just to work
dolittle/Runtime pull request #503
Opened 2021-03-24 18:20 UTC by woksin

2021-03-28 12:30 UTC, woksin commented
@jakhog This should be ready now. I'm just working on specs

2021-03-29 12:17 UTC, jakhog requested changes
Mostly small things. If there is one thing to take out and discuss is the support of "complex" property selector expressions in the keyselector. In my mind we should not support it until we decide on a standard way to do it - to not break it in the future.

2021-03-29 12:17 UTC, jakhog commented on Specifications/Events.Processing/Projections/for_ProjectionKeys/when_type_is_property.cs
> +        It should_have_the_correct_key = () => key.Value.ShouldEqual("property");
Maybe give the property another value just to be sure we don't make any silly mistakes

2021-03-29 12:17 UTC, jakhog commented on Source/Events.Processing/Projections/EventProcessor.cs
> +                return new FailedProcessing("Could not get projection key");
Would be nice to know what key and event failed here.

2021-03-29 12:17 UTC, jakhog commented on Source/Events.Processing/Projections/ProjectionsService.cs
> +                if (!tenantsAndComparisonResult.TryGetValue(tenant, out var comparisonResult)) return;
It seems something terrible has gone wrong if the tenant is not in this dictionary?

2021-03-29 12:17 UTC, jakhog commented on Source/Events.Processing/Projections/ProjectionsService.cs
> +                }
It seems we should do this in the opposite order? If the "new" definition is persisted - but the projections are not dropped. They will have a wrong old state - and not be replayed on next connection right?

2021-03-29 12:57 UTC, woksin commented on Source/Events.Processing/Filters/FiltersProtocol.cs
> +    }
yes 👍

2021-03-29 12:58 UTC, woksin commented on Source/Events.Processing/Projections/CompareProjectionDefinitionsForAllTenants.cs
> +                    false => new ProjectionDefinitionComparisonResult()
Could do that yes

2021-03-29 12:58 UTC, woksin commented on Source/Events.Processing/Projections/CompareProjectionDefinitionsForAllTenants.cs
> +                result = new ProjectionDefinitionComparisonResult("The initial projection state is not the same as the persisted definition");
Yes, that is nIce. We'll do that

2021-03-29 13:05 UTC, woksin commented on Source/Events.Processing/Projections/CompareProjectionDefinitionsForAllTenants.cs
> +        }
It's to get nice error messages

2021-03-29 13:23 UTC, woksin commented on Source/Events.Processing/Projections/CompareProjectionDefinitionsForAllTenants.cs
> +                return true;
Yes I agree

2021-03-29 14:32 UTC, jakhog approved these changes

2021-03-29 14:33 UTC, merged